# sets maximal velocity and acceleration values along the trajectory
dynamic_params: {
# v:4, a:4
  max_v: 7.0,
  max_a: 7.0
}

# Provides the location of waypoints to plan trajectory through
# (x,y)=(0,0) is center of flight arena
# Meters, Radians
# Do NOT put -1.0, write -1.01 instead, otherwise it removes the constraint
# Last waypoint needs velocity and acceleration at 0!

#################################################
waypoints: {
  '0': {
    pos: {
      x: 0.0,
      y: -1.01,
      z: 2.2,
      h: 1.57
    }
  },
  # Do NOT put perching point to an another index than 1 for now!!
  '1': {
    pos: {
      x: 0.0,
      y: 3.0,
      z: 2.0,
      h: 1.57
    },
  },

  '2': {
    pos: {
      x: 0.0,
      y: -2.0,
      z: 2.00,
      h: 1.57
    },
    vel :{
      x: 0.0,
      y: 0.0,
      z: 0.0,
      h: 0.0
    },
    acc: {
      x: 0.0,
      y: 0.0,
      z: 0.0,
      h: 0.0
    }
  }
}

# {
#   '0': {
#     pos: {
#       x: 1.0,
#       y: 0.0,
#       z: 2.0,
#       h: 0.1
#     }
#   },
#   '1': {
#     pos: {
#       x: 1.0,
#       y: 1.5,
#       z: 2.0,
#       h: 0.1
#     }
#   },
#   '2': {
#     pos: {
#       x: 0.0,
#       y: 1.5,
#       z: 2.0,
#       h: 1.6 #0.1
#     }
#   },
#   '3': {
#     pos: {
#       x: 0.0,
#       y: -1.5,
#       z: 2.0,
#       h: 3.14 #0.1
#     }
#   },
#   '4': {
#     pos: {
#       x: 1.0,
#       y: -1.5,
#       z: 2.0,
#       h: 4.71 #0.1
#     }
#   },
#   '5': {
#     pos: {
#       x: 1.0,
#       y: 0.0,
#       z: 2.0,
#       h: 0.1
#     }
#   },
#   '6': {
#     pos: {
#       x: 0.0,
#       y: 0.0,
#       z: 3.0,
#       h: 0.1
#     },
#     vel :{
#       x: 0.0,
#       y: 0.0,
#       z: 0.0,
#       h: 0.0
#     },
#     acc: {
#       x: 0.0,
#       y: 0.0,
#       z: 0.0,
#       h: 0.0
#     }
#   }
# }

